### ISSUE TITLE
Video call sample request

### ISSUE THREAD

**Issue by hyounoo** [Azure-Samples/communication-services-ios-quickstarts#2]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
Please provide video call sample or document
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ddematheu2** [comment]
Video sample is currently in private preview: https://docs.microsoft.com/en-us/azure/communication-services/samples/calling-hero-sample?pivots=platform-ios
